# Generated by Django 5.2.15 on 2026-07-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assignment_expected_result_assignment_setup_sql'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Для карты освоения по темам. Без темы вопрос в карту не попадает.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.topic', verbose_name='тема'),
        ),
    ]
