# Generated by Django 5.2.17 on 2026-09-06 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_question_topic"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "type"], name="idx_assignment_course_type"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["status", "-submitted_at"], name="idx_submission_status"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "assignment"], name="idx_submission_user_task"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["user", "test", "-score"], name="idx_attempt_user_test"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["test", "is_passed"], name="idx_attempt_test_passed"
            ),
        ),
    ]
