# Generated by Django 5.2.17 on 2026-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_assignment_idx_assignment_course_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={
                "ordering": ["order_index"],
                "verbose_name": "вариант ответа",
                "verbose_name_plural": "варианты ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="answersubmission",
            options={
                "verbose_name": "ответ на вопрос",
                "verbose_name_plural": "ответы на вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={"verbose_name": "задание", "verbose_name_plural": "задания"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order_index"],
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "verbose_name": "сдача задания",
                "verbose_name_plural": "сдачи заданий",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "тест", "verbose_name_plural": "тесты"},
        ),
        migrations.AlterModelOptions(
            name="testattempt",
            options={
                "verbose_name": "попытка теста",
                "verbose_name_plural": "попытки тестов",
            },
        ),
    ]
