# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_alter_answeroption_options_and_more"),
        ("courses", "0003_alter_course_author_alter_course_cover_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="верный"),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="order_index",
            field=models.IntegerField(verbose_name="порядок"),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assessments.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="answer_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessments.answeroption",
                verbose_name="выбранный вариант",
            ),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assessments.testattempt",
                verbose_name="попытка",
            ),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True, verbose_name="верно"),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assessments.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="text_answer",
            field=models.TextField(blank=True, null=True, verbose_name="текст ответа"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="создано"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="условие"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="expected_result",
            field=models.JSONField(
                blank=True, null=True, verbose_name="эталонный результат"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="expected_sql",
            field=models.TextField(
                blank=True, null=True, verbose_name="эталонный запрос"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="is_final",
            field=models.BooleanField(default=False, verbose_name="итоговое"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="courses.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="level",
            field=models.CharField(max_length=50, verbose_name="уровень"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.IntegerField(verbose_name="максимум баллов"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="setup_sql",
            field=models.TextField(
                blank=True, null=True, verbose_name="подготовка данных"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.CharField(max_length=50, verbose_name="тип"),
        ),
        migrations.AlterField(
            model_name="question",
            name="order_index",
            field=models.IntegerField(verbose_name="порядок"),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.IntegerField(verbose_name="баллов"),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.test",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="формулировка"),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(max_length=50, verbose_name="тип"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assessments.assignment",
                verbose_name="задание",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="отзыв"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_url",
            field=models.TextField(blank=True, null=True, verbose_name="файл"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="проверено"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="graded_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="проверил",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="балл",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="sql_query",
            field=models.TextField(
                blank=True, null=True, verbose_name="запрос студента"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(max_length=50, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="сдано"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="text_answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="текстовый ответ"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="pass_score",
            field=models.IntegerField(verbose_name="порог сдачи, %"),
        ),
        migrations.AlterField(
            model_name="test",
            name="time_limit_sec",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ограничение, сек"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="завершена"),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="is_passed",
            field=models.BooleanField(blank=True, null=True, verbose_name="сдан"),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="балл",
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="начата"
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="assessments.test",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
    ]
