# Generated by Django 5.2.17 on 2026-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_alter_answeroption_is_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="level",
            field=models.CharField(
                choices=[
                    ("basic", "Начальный"),
                    ("medium", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                max_length=50,
                verbose_name="уровень",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="type",
            field=models.CharField(
                choices=[
                    ("sql", "SQL-запрос"),
                    ("ddl", "Создание структуры (DDL)"),
                    ("file", "Файл"),
                    ("text", "Текст"),
                ],
                max_length=50,
                verbose_name="тип",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Одиночный выбор"),
                    ("multiple", "Множественный выбор"),
                    ("text", "Свободный ответ"),
                    ("sql", "SQL-запрос"),
                ],
                default="single",
                max_length=50,
                verbose_name="тип",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "На проверке"),
                    ("graded", "Оценено"),
                    ("returned", "На доработке"),
                ],
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
