# Generated by Django 5.2.17 on 2026-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pseudonymous_login_and_consent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "роль", "verbose_name_plural": "роли"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
