# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_role_options_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(max_length=30, unique=True, verbose_name="код"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(blank=True, null=True, verbose_name="аватар"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="доступ в админку"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="последний вход"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1, verbose_name="уровень"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.role",
                verbose_name="роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="изменён"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="xp",
            field=models.IntegerField(default=0, verbose_name="XP"),
        ),
    ]
