# Generated by Django 5.2.17 on 2026-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "курсы"},
        ),
        migrations.AlterModelOptions(
            name="courserating",
            options={
                "verbose_name": "отзыв о курсе",
                "verbose_name_plural": "отзывы о курсах",
            },
        ),
        migrations.AlterModelOptions(
            name="coursetopic",
            options={
                "verbose_name": "тема курса",
                "verbose_name_plural": "темы курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order_index"],
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order_index"],
                "verbose_name": "модуль",
                "verbose_name_plural": "модули",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "тема", "verbose_name_plural": "темы"},
        ),
    ]
