# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_courserating_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover_url",
            field=models.TextField(blank=True, null=True, verbose_name="обложка"),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликован"),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(max_length=50, verbose_name="уровень"),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="семестр"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="адрес (slug)"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="отзыв"),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="оставлен"
            ),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="rating",
            field=models.IntegerField(verbose_name="оценка"),
        ),
        migrations.AlterField(
            model_name="courserating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="coursetopic",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_topics",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="coursetopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_courses",
                to="courses.topic",
                verbose_name="тема",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="est_minutes",
            field=models.IntegerField(blank=True, null=True, verbose_name="время, мин"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
                verbose_name="модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order_index",
            field=models.IntegerField(verbose_name="порядок"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="theory_content",
            field=models.TextField(blank=True, null=True, verbose_name="теория"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="xp_reward",
            field=models.IntegerField(default=0, verbose_name="награда XP"),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="module",
            name="order_index",
            field=models.IntegerField(verbose_name="порядок"),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="module",
            name="week_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="неделя"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="код"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=100, verbose_name="название"),
        ),
    ]
