# Generated by Django 5.2.17 on 2026-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_author_alter_course_cover_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("basic", "Начальный"),
                    ("medium", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                max_length=50,
                verbose_name="уровень",
            ),
        ),
    ]
