# Generated by Django 5.2.17 on 2026-09-07 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="coauthors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Видят курс, правят содержание и получают доступ к аналитике по нему.",
                related_name="cocourses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="соавторы",
            ),
        ),
    ]
