# Generated by Django 5.2.15 on 2026-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='comment_is_anonymous',
            field=models.BooleanField(default=False, help_text='Преподаватель увидит текст комментария без указания автора. На оценки понятности и трудности не влияет — они всегда привязаны к студенту.', verbose_name='комментарий анонимно'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
