# Generated by Django 5.2.15 on 2026-08-02 08:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_reflection_anonymous_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Номер группы, например «ИСТ-21».', max_length=100, verbose_name='название')),
                ('note', models.TextField(blank=True, help_text='Для себя: семестр, поток, что угодно.', verbose_name='заметка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(blank=True, db_table='study_group_students', help_text='Кто входит в группу. В ведомость попадут те из них, кто записан на выбранный курс.', related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='студенты')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'db_table': 'study_groups',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'name'), name='uniq_group_name_per_teacher')],
            },
        ),
    ]
