# Generated by Django 5.2.17 on 2026-09-06 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0003_studygroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_activity_user_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["created_at"], name="idx_activity_created"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "user"], name="idx_enrollment_course_user"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["user", "status"], name="idx_progress_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["lesson", "status"], name="idx_progress_lesson_status"
            ),
        ),
    ]
