# Generated by Django 5.2.17 on 2026-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_activity_idx_activity_user_recent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "событие", "verbose_name_plural": "события"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "запись на курс",
                "verbose_name_plural": "записи на курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={
                "verbose_name": "прогресс по уроку",
                "verbose_name_plural": "прогресс по урокам",
            },
        ),
        migrations.AlterModelOptions(
            name="reflection",
            options={"verbose_name": "рефлексия", "verbose_name_plural": "рефлексии"},
        ),
    ]
