# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_author_alter_course_cover_url_and_more"),
        ("learning", "0005_alter_activity_options_alter_enrollment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="когда"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="entity_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="идентификатор объекта"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="entity_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="объект"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="подробности"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(max_length=50, verbose_name="тип"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="завершён"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="записан"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(max_length=50, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="завершён"),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="начат"),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="status",
            field=models.CharField(max_length=50, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="time_spent_sec",
            field=models.IntegerField(default=0, verbose_name="время, сек"),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="заходов"),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="clarity_rating",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="понятность"
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="комментарий"),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="оставлена"
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="difficulty_rating",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="трудность"
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reflections",
                to="courses.lesson",
                verbose_name="урок",
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="изменена"),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reflections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
    ]
