# Generated by Django 5.2.17 on 2026-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0006_alter_activity_created_at_alter_activity_entity_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("lesson_view", "Просмотр урока"),
                    ("lesson_complete", "Завершение урока"),
                    ("test_start", "Начало теста"),
                    ("test_finish", "Завершение теста"),
                    ("sql_run", "Запрос в тренажёре"),
                    ("submission", "Сдача задания"),
                    ("achievement", "Достижение"),
                    ("reflection", "Рефлексия"),
                ],
                max_length=50,
                verbose_name="тип",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Учится"),
                    ("completed", "Завершил"),
                    ("dropped", "Бросил"),
                ],
                max_length=50,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Не начат"),
                    ("in_progress", "В процессе"),
                    ("completed", "Завершён"),
                ],
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
