# Generated by Django 5.2.17 on 2026-09-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_alter_activity_type_alter_enrollment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("lesson_view", "Просмотр урока"),
                    ("lesson_complete", "Завершение урока"),
                    ("test_start", "Начало теста"),
                    ("test_finish", "Завершение теста"),
                    ("sql_run", "Запрос в тренажёре"),
                    ("sql_error", "Ошибка в SQL"),
                    ("submission", "Сдача задания"),
                    ("achievement", "Достижение"),
                    ("reflection", "Рефлексия"),
                ],
                max_length=50,
                verbose_name="тип",
            ),
        ),
    ]
