# Generated by Django 5.2.17 on 2026-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"verbose_name": "достижение", "verbose_name_plural": "достижения"},
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={
                "verbose_name": "полученное достижение",
                "verbose_name_plural": "полученные достижения",
            },
        ),
    ]
