# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_alter_achievement_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="код"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="значок"
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(max_length=150, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="xp_reward",
            field=models.IntegerField(default=0, verbose_name="награда XP"),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awarded_to",
                to="gamification.achievement",
                verbose_name="достижение",
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="awarded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="получено"
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
